version: "3.9"

services:
  poc:
    container_name: poc
    image: roboticsplus/nodejs:1.0.0
    ports:
      - 4050:4050
    volumes:
      - ../:/home/rpl/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/rpl/.ssh
      - ~/.gitconfig:/home/rpl/.gitconfig
    environment:
      - PORT=4050
      - REACT_APP_CENTERLATITUDE=-37.67543797703169
      - REACT_APP_CENTERLONGITUDE=176.0563796050459
      - REACT_APP_STARTZOOM=17
      - REACT_APP_MAXZOOM=23
      - REACT_APP_TILEURL=/tiles/data/rp-test/{z}/{x}/{y}.png
